# Site settings
title: JJEONG BLOG
description: jjeong's blog
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: YoonJeong
user_description: I love music and cat.
user_title: Software Engineer
email: jjeong7097@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
